### ISSUE TITLE
Assets naming issues

### ISSUE THREAD

**Issue by blackgear** [suisei-cn/starbuttons#12]
I'd like to proposal some variants:

1. sha256_digest.mp3
2. numeric_id.mp3
3. dialogue_text_in_roma.mp3
4. dialogue_text_in_english.mp3

3 and 4 may suffer from same dialogue in different sources. 4 also invoke some translation problems....

We can put all metadata in assets.json, including source uri and clip timing point.

**Comment by outloudvi** [comment]
Agree. I'd go for numeric id or a shorter digest (since sha256 is too long and we don't really to verify the integrity).
