### ISSUE TITLE
Find a better alternative of { outline: none; }

### ISSUE THREAD

**Issue by outloudvi** [suisei-cn/starbuttons#42]
In 363a73d2bb61fc5841912369ea9beaaa9ceb13dd we removed outlines for focused elements due to design considerations. Since we have `aria-label` stuffs, we thought that the removal of outline would not affect accessibility a lot. However, as said by <http://outlinenone.com/>, it DOES have a huge effect on a11y. As a site that stresses a11y, we need to find a alternataive of outline.

**Comment by stroudn1** [comment]
Hello! I'd recommend keeping the outline for keyboard focus but if it's decided to keep them out for design purposes - change the design for an incredibly visible focus indicator (i.e. change background color on focus + hover)

[How to Design Useful and Usable Focus Indicators](https://www.deque.com/blog/give-site-focus-tips-designing-usable-focus-indicators/)

Hope this helps! Have a great weekend

**Comment by outloudvi** [comment]
Thanks for your suggesstion, @stroudn1! We are also considering the visible focus indicator. Changing background color is a good idea. Also, currently we bold the text on hovering, so maybe we can just copy the `:hover` behaviour to `:focus`.
