### ISSUE TITLE
Choosing a favicon for Starbuttons

### ISSUE THREAD

**Issue by outloudvi** [suisei-cn/starbuttons#65]
It's a good idea to give starbuttons a favicon. Currently the idea is using a "comet" emoji icon ([U+2604](https://unicode.org/emoji/charts/full-emoji-list.html#2604)) from some vendor.

Here are some suggestions that we can use:

EmojiDex: ![](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/emojidex/112/comet_2604.png) ([License](https://www.emojidex.com/emojidex/emojidex_open_license))

Twitter: ![](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/twitter/248/comet_2604.png) ([License](https://github.com/twitter/twemoji/blob/gh-pages/LICENSE-GRAPHICS))

Microsoft: ![](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/microsoft/209/comet_2604.png) ([License](https://docs.microsoft.com/en-us/typography/fonts/font-faq))

Google: ![](https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/google/241/comet_2604.png) ([License](https://github.com/googlefonts/noto-emoji/blob/master/LICENSE))

**Comment by Hoshimachiyuri** [comment]
I personally prefer the Microsoft version.（
