### ISSUE TITLE
千里迢迢来gayhub，我就为了留下一句草

### ISSUE THREAD

**Issue by Swift-Lee** [suisei-cn/starbuttons#7]
等一个有能dd让星姐看到这个仓库

**Comment by outloudvi** [comment]
辛苦了。赠您一个 `suisei-anti-detected` 的 label 作为回礼。

**Comment by Swift-Lee** [comment]
兄啊，我不是anti，我close这个issue还不好吗

**Comment by outloudvi** [comment]
@Swift-Lee 没关系，我也是（逃

**Comment by Swift-Lee** [comment]
@outloudvi 那没事了，原来是自己人（狂喜
